//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: ICC_model
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translators: , pycml: , optimize: )
//! on Tue Jul 20 13:11:51 2021
//! 
//! <autogenerated>

#include "corrias_buist_2008.hpp"
#include <cmath>
#include <cassert>
#include <memory>
#include "Exception.hpp"
#include "OdeSystemInformation.hpp"
#include "RegularStimulus.hpp"
#include "HeartConfig.hpp"
#include "IsNan.hpp"
#include "MathsCustomFunctions.hpp"

    Cellcorrias_buist_2008FromCellML::Cellcorrias_buist_2008FromCellML(boost::shared_ptr<AbstractIvpOdeSolver> pSolver, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus)
        : AbstractCardiacCell(
                pSolver,
                22,
                0,
                pIntracellularStimulus)
    {
        // Time units: millisecond
        // 
        this->mpSystemInfo = OdeSystemInformation<Cellcorrias_buist_2008FromCellML>::Instance();
        Init();

    }
    
    Cellcorrias_buist_2008FromCellML::~Cellcorrias_buist_2008FromCellML()
    {
    }
    
    double Cellcorrias_buist_2008FromCellML::GetIIonic(const std::vector<double>* pStateVariables)
    {
        // For state variable interpolation (SVI) we read in interpolated state variables,
        // otherwise for ionic current interpolation (ICI) we use the state variables of this model (node).
        if (!pStateVariables) pStateVariables = &rGetStateVariables();
        const std::vector<double>& rY = *pStateVariables;
        double var_chaste_interface__ICC_Membrane__Vm = (mSetVoltageDerivativeToZero ? this->mFixedVoltage : rY[0]);
        // Units: millivolt; Initial value: -67
        double var_chaste_interface__ICC_Membrane__Ca_i = rY[1];
        // Units: millimolar; Initial value: 0.00000993087
        double var_chaste_interface__d_Ltype__d_Ltype = rY[2];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_Ltype__f_Ltype = rY[3];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__f_ca_Ltype__f_ca_Ltype = rY[4];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_VDDR__d_VDDR = rY[5];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_VDDR__f_VDDR = rY[6];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_CaCl__d_CaCl = rY[7];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__d_ERG__d_ERG = rY[8];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__d_kv11__d_kv11 = rY[9];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_kv11__f_kv11 = rY[10];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_Na__d_Na = rY[11];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_Na__f_Na = rY[12];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_NSCC__d_NSCC = rY[13];
        // Units: dimensionless; Initial value: 0
        
        const double var_Environment__T = 310.0; // Temperature_units
        const double var_Environment__T_exp = 297.0; // Temperature_units
        const double var_Environment__F = 96.4846; // F_units
        const double var_Environment__R = 8.3143999999999991; // R_units
        const double var_Environment__Ca_o = 2.5; // millimolar
        const double var_Environment__Na_o = 137.0; // millimolar
        const double var_Environment__K_o = 7.0; // millimolar
        const double var_Environment__Cl_o = 134.0; // millimolar
        const double var_Environment__T_correction_BK = 1.1000000000000001 * (var_Environment__T - var_Environment__T_exp); // conductance_units
        const double var_Environment__RToF = (var_Environment__R * var_Environment__T) / var_Environment__F; // voltage_units
        const double var_ICC_Membrane__Vm = var_chaste_interface__ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__Ca_i = var_chaste_interface__ICC_Membrane__Ca_i; // millimolar
        const double var_ICC_Membrane__Na_i = 30.0; // millimolar
        const double var_ICC_Membrane__K_i = 120.0; // millimolar
        const double var_ICC_Membrane__Cl_i = 88.0; // millimolar
        const double var_ICC_Membrane__Ca_o = var_Environment__Ca_o; // millimolar
        const double var_ICC_Membrane__Na_o = var_Environment__Na_o; // millimolar
        const double var_ICC_Membrane__K_o = var_Environment__K_o; // millimolar
        const double var_ICC_Membrane__Cl_o = var_Environment__Cl_o; // millimolar
        const double var_ICC_Membrane__T_correction_BK = var_Environment__T_correction_BK; // conductance_units
        const double var_ICC_Membrane__RToF = var_Environment__RToF; // voltage_units
        const double var_I_Na__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_Na__Na_i = var_ICC_Membrane__Na_i; // millimolar
        const double var_I_Na__Na_o = var_ICC_Membrane__Na_o; // millimolar
        const double var_I_Na__E_Na = var_I_Na__RToF * log(var_I_Na__Na_o / var_I_Na__Na_i); // voltage_units
        const double var_ICC_Membrane__f_Na = var_chaste_interface__f_Na__f_Na; // dimensionless
        const double var_I_Na__f_Na = var_ICC_Membrane__f_Na; // dimensionless
        const double var_I_Na__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_Na = var_chaste_interface__d_Na__d_Na; // dimensionless
        const double var_I_Na__d_Na = var_ICC_Membrane__d_Na; // dimensionless
        const double var_I_Na__G_max_Na = 20.0; // conductance_units
        const double var_I_Na__I_Na = var_I_Na__G_max_Na * var_I_Na__f_Na * var_I_Na__d_Na * (var_I_Na__Vm - var_I_Na__E_Na); // current_units
        const double var_ICC_Membrane__f_Ltype = var_chaste_interface__f_Ltype__f_Ltype; // dimensionless
        const double var_I_Ltype__f_Ltype = var_ICC_Membrane__f_Ltype; // dimensionless
        const double var_ICC_Membrane__d_Ltype = var_chaste_interface__d_Ltype__d_Ltype; // dimensionless
        const double var_I_Ltype__d_Ltype = var_ICC_Membrane__d_Ltype; // dimensionless
        const double var_I_Ltype__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_I_Ltype__Ca_o = var_ICC_Membrane__Ca_o; // millimolar
        const double var_I_Ltype__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_Ltype__E_Ca = 0.5 * var_I_Ltype__RToF * log(var_I_Ltype__Ca_o / var_I_Ltype__Ca_i); // voltage_units
        const double var_ICC_Membrane__f_ca_Ltype = var_chaste_interface__f_ca_Ltype__f_ca_Ltype; // dimensionless
        const double var_I_Ltype__f_ca_Ltype = var_ICC_Membrane__f_ca_Ltype; // dimensionless
        const double var_I_Ltype__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_Ltype__G_max_Ltype = 2.0; // conductance_units
        const double var_I_Ltype__I_Ltype = var_I_Ltype__G_max_Ltype * var_I_Ltype__f_Ltype * var_I_Ltype__d_Ltype * var_I_Ltype__f_ca_Ltype * (var_I_Ltype__Vm - var_I_Ltype__E_Ca); // current_units
        const double var_ICC_Membrane__f_VDDR = var_chaste_interface__f_VDDR__f_VDDR; // dimensionless
        const double var_I_VDDR__f_VDDR = var_ICC_Membrane__f_VDDR; // dimensionless
        const double var_I_VDDR__Ca_o = var_ICC_Membrane__Ca_o; // millimolar
        const double var_I_VDDR__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_VDDR__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_I_VDDR__E_Ca = 0.5 * var_I_VDDR__RToF * log(var_I_VDDR__Ca_o / var_I_VDDR__Ca_i); // voltage_units
        const double var_I_VDDR__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_VDDR__G_max_VDDR = 3.0; // conductance_units
        const double var_ICC_Membrane__d_VDDR = var_chaste_interface__d_VDDR__d_VDDR; // dimensionless
        const double var_I_VDDR__d_VDDR = var_ICC_Membrane__d_VDDR; // dimensionless
        const double var_I_VDDR__I_VDDR = var_I_VDDR__G_max_VDDR * var_I_VDDR__f_VDDR * var_I_VDDR__d_VDDR * (var_I_VDDR__Vm - var_I_VDDR__E_Ca); // current_units
        const double var_I_kv11__G_max_kv11 = 6.2999999999999998; // conductance_units
        const double var_ICC_Membrane__f_kv11 = var_chaste_interface__f_kv11__f_kv11; // dimensionless
        const double var_I_kv11__f_kv11 = var_ICC_Membrane__f_kv11; // dimensionless
        const double var_I_kv11__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_kv11 = var_chaste_interface__d_kv11__d_kv11; // dimensionless
        const double var_I_kv11__d_kv11 = var_ICC_Membrane__d_kv11; // dimensionless
        const double var_I_kv11__K_i = var_ICC_Membrane__K_i; // millimolar
        const double var_I_kv11__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_kv11__K_o = var_ICC_Membrane__K_o; // millimolar
        const double var_I_kv11__E_K = var_I_kv11__RToF * log(var_I_kv11__K_o / var_I_kv11__K_i); // voltage_units
        const double var_I_kv11__I_kv11 = var_I_kv11__G_max_kv11 * var_I_kv11__f_kv11 * var_I_kv11__d_kv11 * (var_I_kv11__Vm - var_I_kv11__E_K); // current_units
        const double var_I_BK__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_BK__T_correction_BK = var_ICC_Membrane__T_correction_BK; // conductance_units
        const double var_I_BK__G_max_BK = 23.0; // conductance_units
        const double var_I_BK__K_i = var_ICC_Membrane__K_i; // millimolar
        const double var_I_BK__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_BK__K_o = var_ICC_Membrane__K_o; // millimolar
        const double var_I_BK__E_K = var_I_BK__RToF * log(var_I_BK__K_o / var_I_BK__K_i); // voltage_units
        const double var_I_BK__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_d_BK__Ca_i = var_I_BK__Ca_i; // millimolar
        const double var_d_BK__Vm = var_I_BK__Vm; // voltage_units
        const double var_d_BK__d_BK = 1.0 / (1.0 + exp((var_d_BK__Vm / (-17.0)) - (2.0 * log(var_d_BK__Ca_i / 0.001)))); // dimensionless
        const double var_I_BK__d_BK = var_d_BK__d_BK; // dimensionless
        const double var_I_BK__I_BK = (var_I_BK__G_max_BK + var_I_BK__T_correction_BK) * var_I_BK__d_BK * (var_I_BK__Vm - var_I_BK__E_K); // current_units
        const double var_I_ERG__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_ERG__G_max_ERG = 2.5; // conductance_units
        const double var_I_ERG__K_o = var_ICC_Membrane__K_o; // millimolar
        const double var_I_ERG__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_ERG__K_i = var_ICC_Membrane__K_i; // millimolar
        const double var_I_ERG__E_K = var_I_ERG__RToF * log(var_I_ERG__K_o / var_I_ERG__K_i); // voltage_units
        const double var_ICC_Membrane__d_ERG = var_chaste_interface__d_ERG__d_ERG; // dimensionless
        const double var_I_ERG__d_ERG = var_ICC_Membrane__d_ERG; // dimensionless
        const double var_I_ERG__I_ERG = var_I_ERG__G_max_ERG * var_I_ERG__d_ERG * (var_I_ERG__Vm - var_I_ERG__E_K); // current_units
        const double var_I_CaCl__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_CaCl = var_chaste_interface__d_CaCl__d_CaCl; // dimensionless
        const double var_I_CaCl__d_CaCl = var_ICC_Membrane__d_CaCl; // dimensionless
        const double var_I_CaCl__Cl_o = var_ICC_Membrane__Cl_o; // millimolar
        const double var_I_CaCl__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_CaCl__Cl_i = var_ICC_Membrane__Cl_i; // millimolar
        const double var_I_CaCl__E_Cl = var_I_CaCl__RToF * log(var_I_CaCl__Cl_i / var_I_CaCl__Cl_o); // voltage_units
        const double var_I_CaCl__G_max_CaCl = 10.1; // conductance_units
        const double var_I_CaCl__I_CaCl = var_I_CaCl__G_max_CaCl * var_I_CaCl__d_CaCl * (var_I_CaCl__Vm - var_I_CaCl__E_Cl); // current_units
        const double var_I_NSCC__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_NSCC = var_chaste_interface__d_NSCC__d_NSCC; // dimensionless
        const double var_I_NSCC__d_NSCC = var_ICC_Membrane__d_NSCC; // dimensionless
        const double var_I_NSCC__K_o = var_ICC_Membrane__K_o; // millimolar
        const double var_I_NSCC__Na_i = var_ICC_Membrane__Na_i; // millimolar
        const double var_I_NSCC__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_NSCC__K_i = var_ICC_Membrane__K_i; // millimolar
        const double var_I_NSCC__NaPerm_o_Kperm = 1.0560750000000001; // dimensionless
        const double var_I_NSCC__Na_o = var_ICC_Membrane__Na_o; // millimolar
        const double var_I_NSCC__E_NSCC = var_I_NSCC__RToF * log((var_I_NSCC__K_o + (var_I_NSCC__Na_o * var_I_NSCC__NaPerm_o_Kperm)) / (var_I_NSCC__K_i + (var_I_NSCC__Na_i * var_I_NSCC__NaPerm_o_Kperm))); // voltage_units
        const double var_I_NSCC__G_max_NSCC = 12.15; // conductance_units
        const double var_I_NSCC__I_NSCC = var_I_NSCC__G_max_NSCC * var_I_NSCC__d_NSCC * (var_I_NSCC__Vm - var_I_NSCC__E_NSCC); // current_units
        const double var_I_bk__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_bk__G_max_bk = 0.14999999999999999; // conductance_units
        const double var_I_bk__K_i = var_ICC_Membrane__K_i; // millimolar
        const double var_I_bk__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_bk__K_o = var_ICC_Membrane__K_o; // millimolar
        const double var_I_bk__E_K = var_I_bk__RToF * log(var_I_bk__K_o / var_I_bk__K_i); // voltage_units
        const double var_I_bk__I_bk = var_I_bk__G_max_bk * (var_I_bk__Vm - var_I_bk__E_K); // current_units
        const double var_ICC_Membrane__I_Na__I_Na = var_I_Na__I_Na; // current_units
        const double var_ICC_Membrane__I_Ltype__I_Ltype = var_I_Ltype__I_Ltype; // current_units
        const double var_ICC_Membrane__I_VDDR__I_VDDR = var_I_VDDR__I_VDDR; // current_units
        const double var_ICC_Membrane__I_kv11__I_kv11 = var_I_kv11__I_kv11; // current_units
        const double var_ICC_Membrane__I_ERG__I_ERG = var_I_ERG__I_ERG; // current_units
        const double var_ICC_Membrane__I_BK__I_BK = var_I_BK__I_BK; // current_units
        const double var_ICC_Membrane__I_CaCl__I_CaCl = var_I_CaCl__I_CaCl; // current_units
        const double var_ICC_Membrane__I_NSCC__I_NSCC = var_I_NSCC__I_NSCC; // current_units
        const double var_ICC_Membrane__I_bk__I_bk = var_I_bk__I_bk; // current_units
        const double var_chaste_interface__I_BK__I_BK = var_ICC_Membrane__I_BK__I_BK; // current_units
        const double var_chaste_interface__I_kv11__I_kv11 = var_ICC_Membrane__I_kv11__I_kv11; // current_units
        const double var_chaste_interface__I_Ltype__I_Ltype = var_ICC_Membrane__I_Ltype__I_Ltype; // current_units
        const double var_chaste_interface__I_NSCC__I_NSCC = var_ICC_Membrane__I_NSCC__I_NSCC; // current_units
        const double var_chaste_interface__I_ERG__I_ERG = var_ICC_Membrane__I_ERG__I_ERG; // current_units
        const double var_chaste_interface__I_bk__I_bk = var_ICC_Membrane__I_bk__I_bk; // current_units
        const double var_chaste_interface__I_VDDR__I_VDDR = var_ICC_Membrane__I_VDDR__I_VDDR; // current_units
        const double var_chaste_interface__I_CaCl__I_CaCl = var_ICC_Membrane__I_CaCl__I_CaCl; // current_units
        const double var_chaste_interface__I_Na__I_Na = var_ICC_Membrane__I_Na__I_Na; // current_units
        const double var_chaste_interface__i_ionic = (1e-10 * var_chaste_interface__I_Na__I_Na) + (1e-10 * var_chaste_interface__I_Ltype__I_Ltype) + (1e-10 * var_chaste_interface__I_VDDR__I_VDDR) + (1e-10 * var_chaste_interface__I_kv11__I_kv11) + (1e-10 * var_chaste_interface__I_ERG__I_ERG) + (1e-10 * var_chaste_interface__I_BK__I_BK) + (1e-10 * var_chaste_interface__I_CaCl__I_CaCl) + (1e-10 * var_chaste_interface__I_NSCC__I_NSCC) + (1e-10 * var_chaste_interface__I_bk__I_bk); // uA_per_cm2
        
        const double i_ionic = var_chaste_interface__i_ionic;
        EXCEPT_IF_NOT(!std::isnan(i_ionic));
        return i_ionic;
    }
    
    void Cellcorrias_buist_2008FromCellML::EvaluateYDerivatives(double var_chaste_interface__Time__time, const std::vector<double>& rY, std::vector<double>& rDY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__ICC_Membrane__Vm = (mSetVoltageDerivativeToZero ? this->mFixedVoltage : rY[0]);
        // Units: millivolt; Initial value: -67
        double var_chaste_interface__ICC_Membrane__Ca_i = rY[1];
        // Units: millimolar; Initial value: 0.00000993087
        double var_chaste_interface__d_Ltype__d_Ltype = rY[2];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_Ltype__f_Ltype = rY[3];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__f_ca_Ltype__f_ca_Ltype = rY[4];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_VDDR__d_VDDR = rY[5];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_VDDR__f_VDDR = rY[6];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_CaCl__d_CaCl = rY[7];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__d_ERG__d_ERG = rY[8];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__d_kv11__d_kv11 = rY[9];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_kv11__f_kv11 = rY[10];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_Na__d_Na = rY[11];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__f_Na__f_Na = rY[12];
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__d_NSCC__d_NSCC = rY[13];
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__PU_unit__Ca_PU = rY[14];
        // Units: millimolar; Initial value: 0.0000902
        double var_chaste_interface__PU_unit__Ca_m = rY[15];
        // Units: millimolar; Initial value: 0.000136
        double var_chaste_interface__PU_unit__Ca_ER = rY[16];
        // Units: millimolar; Initial value: 0.007299
        double var_chaste_interface__PU_unit__ADP_m = rY[17];
        // Units: millimolar; Initial value: 2.60093454
        double var_chaste_interface__PU_unit__ADP_i = rY[18];
        // Units: millimolar; Initial value: 0.0077282
        double var_chaste_interface__PU_unit__NADH_m = rY[19];
        // Units: millimolar; Initial value: 0.101476
        double var_chaste_interface__PU_unit__h = rY[20];
        // Units: dimensionless; Initial value: 0.9397
        double var_chaste_interface__PU_unit__deltaPsi = rY[21];
        // Units: voltage_units; Initial value: 164.000044
        
        
        // Mathematics
        double d_dt_chaste_interface__ICC_Membrane__Vm;
        const double var_Environment__T = 310.0; // Temperature_units
        const double var_Environment__T_exp = 297.0; // Temperature_units
        const double var_Environment__F = 96.4846; // F_units
        const double var_Environment__R = 8.3143999999999991; // R_units
        const double var_Environment__Q10Ca = 2.1000000000000001; // dimensionless
        const double var_Environment__Q10K = 1.5; // dimensionless
        const double var_Environment__Q10Na = 2.4500000000000002; // dimensionless
        const double var_Environment__Ca_o = 2.5; // millimolar
        const double var_Environment__T_correction_Na = pow(var_Environment__Q10Na, (var_Environment__T - var_Environment__T_exp) / 10.0); // dimensionless
        const double var_Environment__T_correction_K = pow(var_Environment__Q10K, (var_Environment__T - var_Environment__T_exp) / 10.0); // dimensionless
        const double var_Environment__T_correction_Ca = pow(var_Environment__Q10Ca, (var_Environment__T - var_Environment__T_exp) / 10.0); // dimensionless
        const double var_Environment__FoRT = var_Environment__F / (var_Environment__R * var_Environment__T); // Inverse_Voltage_units
        const double var_Environment__RToF = (var_Environment__R * var_Environment__T) / var_Environment__F; // voltage_units
        const double var_ICC_Membrane__Vol = 9.9999999999999998e-13; // volume_units
        const double var_ICC_Membrane__P_cyto = 0.69999999999999996; // dimensionless
        const double var_ICC_Membrane__V_cyto = var_ICC_Membrane__Vol * var_ICC_Membrane__P_cyto; // volume_units
        const double var_ICC_Membrane__fc = 0.01; // dimensionless
        const double var_ICC_Membrane__Vm = var_chaste_interface__ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__Ca_i = var_chaste_interface__ICC_Membrane__Ca_i; // millimolar
        const double var_ICC_Membrane__Na_i = 30.0; // millimolar
        const double var_ICC_Membrane__Ca_o = var_Environment__Ca_o; // millimolar
        const double var_ICC_Membrane__T_correction_Ca = var_Environment__T_correction_Ca; // dimensionless
        const double var_ICC_Membrane__T_correction_Na = var_Environment__T_correction_Na; // dimensionless
        const double var_ICC_Membrane__T_correction_K = var_Environment__T_correction_K; // dimensionless
        const double var_ICC_Membrane__RToF = var_Environment__RToF; // voltage_units
        const double var_ICC_Membrane__FoRT = var_Environment__FoRT; // Inverse_Voltage_units
        const double var_ICC_Membrane__F = var_Environment__F; // F_units
        const double var_ICC_Membrane__Ca_PU = var_chaste_interface__PU_unit__Ca_PU; // millimolar
        const double var_PU_unit__Ca_PU = var_ICC_Membrane__Ca_PU; // millimolar
        const double var_PU_unit__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_PU_unit__J_max_leak = 0.01; // rate_constants_units
        const double var_PU_unit__J_leak = var_PU_unit__J_max_leak * (var_PU_unit__Ca_PU - var_PU_unit__Ca_i); // millimolar_per_second
        const double var_ICC_Membrane__J_leak = var_PU_unit__J_leak; // millimolar_per_second
        const double var_ICC_Membrane__f_Na = var_chaste_interface__f_Na__f_Na; // dimensionless
        const double var_I_Na__f_Na = var_ICC_Membrane__f_Na; // dimensionless
        const double var_I_Na__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_Na = var_chaste_interface__d_Na__d_Na; // dimensionless
        const double var_I_Na__d_Na = var_ICC_Membrane__d_Na; // dimensionless
        const double var_ICC_Membrane__f_Ltype = var_chaste_interface__f_Ltype__f_Ltype; // dimensionless
        const double var_I_Ltype__f_Ltype = var_ICC_Membrane__f_Ltype; // dimensionless
        const double var_ICC_Membrane__d_Ltype = var_chaste_interface__d_Ltype__d_Ltype; // dimensionless
        const double var_I_Ltype__d_Ltype = var_ICC_Membrane__d_Ltype; // dimensionless
        const double var_I_Ltype__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_I_Ltype__Ca_o = var_ICC_Membrane__Ca_o; // millimolar
        const double var_I_Ltype__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_Ltype__E_Ca = 0.5 * var_I_Ltype__RToF * log(var_I_Ltype__Ca_o / var_I_Ltype__Ca_i); // voltage_units
        const double var_ICC_Membrane__f_ca_Ltype = var_chaste_interface__f_ca_Ltype__f_ca_Ltype; // dimensionless
        const double var_I_Ltype__f_ca_Ltype = var_ICC_Membrane__f_ca_Ltype; // dimensionless
        const double var_I_Ltype__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_Ltype__G_max_Ltype = 2.0; // conductance_units
        const double var_I_Ltype__I_Ltype = var_I_Ltype__G_max_Ltype * var_I_Ltype__f_Ltype * var_I_Ltype__d_Ltype * var_I_Ltype__f_ca_Ltype * (var_I_Ltype__Vm - var_I_Ltype__E_Ca); // current_units
        const double var_ICC_Membrane__I_Ltype = var_I_Ltype__I_Ltype; // current_units
        const double var_ICC_Membrane__f_VDDR = var_chaste_interface__f_VDDR__f_VDDR; // dimensionless
        const double var_I_VDDR__f_VDDR = var_ICC_Membrane__f_VDDR; // dimensionless
        const double var_I_VDDR__Ca_o = var_ICC_Membrane__Ca_o; // millimolar
        const double var_I_VDDR__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_I_VDDR__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_I_VDDR__E_Ca = 0.5 * var_I_VDDR__RToF * log(var_I_VDDR__Ca_o / var_I_VDDR__Ca_i); // voltage_units
        const double var_I_VDDR__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_I_VDDR__G_max_VDDR = 3.0; // conductance_units
        const double var_ICC_Membrane__d_VDDR = var_chaste_interface__d_VDDR__d_VDDR; // dimensionless
        const double var_I_VDDR__d_VDDR = var_ICC_Membrane__d_VDDR; // dimensionless
        const double var_I_VDDR__I_VDDR = var_I_VDDR__G_max_VDDR * var_I_VDDR__f_VDDR * var_I_VDDR__d_VDDR * (var_I_VDDR__Vm - var_I_VDDR__E_Ca); // current_units
        const double var_ICC_Membrane__I_VDDR = var_I_VDDR__I_VDDR; // current_units
        const double var_ICC_Membrane__f_kv11 = var_chaste_interface__f_kv11__f_kv11; // dimensionless
        const double var_I_kv11__f_kv11 = var_ICC_Membrane__f_kv11; // dimensionless
        const double var_I_kv11__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_kv11 = var_chaste_interface__d_kv11__d_kv11; // dimensionless
        const double var_I_kv11__d_kv11 = var_ICC_Membrane__d_kv11; // dimensionless
        const double var_I_ERG__Vm = var_ICC_Membrane__Vm; // voltage_units
        const double var_ICC_Membrane__d_ERG = var_chaste_interface__d_ERG__d_ERG; // dimensionless
        const double var_I_ERG__d_ERG = var_ICC_Membrane__d_ERG; // dimensionless
        const double var_ICC_Membrane__d_CaCl = var_chaste_interface__d_CaCl__d_CaCl; // dimensionless
        const double var_I_CaCl__d_CaCl = var_ICC_Membrane__d_CaCl; // dimensionless
        const double var_ICC_Membrane__d_NSCC = var_chaste_interface__d_NSCC__d_NSCC; // dimensionless
        const double var_I_NSCC__d_NSCC = var_ICC_Membrane__d_NSCC; // dimensionless
        const double var_J_PMCA__J_max_PMCA = 0.088464000000000001; // millimolar_per_second
        const double var_J_PMCA__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_J_PMCA__J_PMCA = (var_J_PMCA__J_max_PMCA * 1.0) / (1.0 + (0.00029799999999999998 / var_J_PMCA__Ca_i)); // millimolar_per_second
        const double var_ICC_Membrane__J_PMCA = var_J_PMCA__J_PMCA; // millimolar_per_second
        const double var_ICC_Membrane__d_Ca_i_d_Time__time = var_ICC_Membrane__fc * (((((-1.0) * var_ICC_Membrane__I_Ltype) + ((-1.0) * var_ICC_Membrane__I_VDDR)) / (2.0 * 1000000.0 * 1000000.0 * var_ICC_Membrane__F * var_ICC_Membrane__V_cyto)) + var_ICC_Membrane__J_leak + ((-1.0) * var_ICC_Membrane__J_PMCA)); // 'millimole per litre per second'
        const double var_d_Ltype__Vm = var_I_Ltype__Vm; // voltage_units
        const double var_d_Ltype__d_inf_Ltype = 1.0 / (1.0 + exp((var_d_Ltype__Vm + 17.0) / (-4.2999999999999998))); // dimensionless
        const double var_d_Ltype__d_Ltype = var_I_Ltype__d_Ltype; // dimensionless
        const double var_I_Ltype__T_correction_Ca = var_ICC_Membrane__T_correction_Ca; // dimensionless
        const double var_d_Ltype__T_correction_Ca = var_I_Ltype__T_correction_Ca; // dimensionless
        const double var_d_Ltype__tau_d_Ltype = var_d_Ltype__T_correction_Ca * 0.001; // time_units
        const double var_d_Ltype__d_d_Ltype_d_Time__time = (var_d_Ltype__d_inf_Ltype - var_d_Ltype__d_Ltype) / var_d_Ltype__tau_d_Ltype; // 'per second'
        const double var_I_Ltype__d_Ltype__d_d_Ltype_d_Time__time = var_d_Ltype__d_d_Ltype_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_Ltype__d_d_Ltype_d_Time__time = var_I_Ltype__d_Ltype__d_d_Ltype_d_Time__time; // ___units_31
        const double var_f_Ltype__Vm = var_I_Ltype__Vm; // voltage_units
        const double var_f_Ltype__f_inf_Ltype = 1.0 / (1.0 + exp((var_f_Ltype__Vm + 43.0) / 8.9000000000000004)); // dimensionless
        const double var_f_Ltype__f_Ltype = var_I_Ltype__f_Ltype; // dimensionless
        const double var_f_Ltype__T_correction_Ca = var_I_Ltype__T_correction_Ca; // dimensionless
        const double var_f_Ltype__tau_f_Ltype = var_f_Ltype__T_correction_Ca * 0.085999999999999993; // time_units
        const double var_f_Ltype__d_f_Ltype_d_Time__time = (var_f_Ltype__f_inf_Ltype - var_f_Ltype__f_Ltype) / var_f_Ltype__tau_f_Ltype; // 'per second'
        const double var_I_Ltype__f_Ltype__d_f_Ltype_d_Time__time = var_f_Ltype__d_f_Ltype_d_Time__time; // ___units_31
        const double var_ICC_Membrane__f_Ltype__d_f_Ltype_d_Time__time = var_I_Ltype__f_Ltype__d_f_Ltype_d_Time__time; // ___units_31
        const double var_f_ca_Ltype__Ca_i = var_I_Ltype__Ca_i; // millimolar
        const double var_f_ca_Ltype__f_ca_inf_Ltype = 1.0 - (1.0 / (1.0 + exp(((var_f_ca_Ltype__Ca_i - 0.0001) - 0.000214) / (-1.31e-05)))); // dimensionless
        const double var_f_ca_Ltype__T_correction_Ca = var_I_Ltype__T_correction_Ca; // dimensionless
        const double var_f_ca_Ltype__tau_f_ca_Ltype = var_f_ca_Ltype__T_correction_Ca * 0.002; // time_units
        const double var_f_ca_Ltype__f_ca_Ltype = var_I_Ltype__f_ca_Ltype; // dimensionless
        const double var_f_ca_Ltype__d_f_ca_Ltype_d_Time__time = (var_f_ca_Ltype__f_ca_inf_Ltype - var_f_ca_Ltype__f_ca_Ltype) / var_f_ca_Ltype__tau_f_ca_Ltype; // 'per second'
        const double var_I_Ltype__f_ca_Ltype__d_f_ca_Ltype_d_Time__time = var_f_ca_Ltype__d_f_ca_Ltype_d_Time__time; // ___units_31
        const double var_ICC_Membrane__f_ca_Ltype__d_f_ca_Ltype_d_Time__time = var_I_Ltype__f_ca_Ltype__d_f_ca_Ltype_d_Time__time; // ___units_31
        const double var_d_VDDR__Vm = var_I_VDDR__Vm; // voltage_units
        const double var_d_VDDR__d_inf_VDDR = 1.0 / (1.0 + exp((var_d_VDDR__Vm + 26.0) / (-6.0))); // dimensionless
        const double var_I_VDDR__T_correction_Ca = var_ICC_Membrane__T_correction_Ca; // dimensionless
        const double var_d_VDDR__T_correction_Ca = var_I_VDDR__T_correction_Ca; // dimensionless
        const double var_d_VDDR__tau_d_VDDR = var_d_VDDR__T_correction_Ca * 0.0060000000000000001; // time_units
        const double var_d_VDDR__d_VDDR = var_I_VDDR__d_VDDR; // dimensionless
        const double var_d_VDDR__d_d_VDDR_d_Time__time = (var_d_VDDR__d_inf_VDDR - var_d_VDDR__d_VDDR) / var_d_VDDR__tau_d_VDDR; // 'per second'
        const double var_I_VDDR__d_VDDR__d_d_VDDR_d_Time__time = var_d_VDDR__d_d_VDDR_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_VDDR__d_d_VDDR_d_Time__time = var_I_VDDR__d_VDDR__d_d_VDDR_d_Time__time; // ___units_31
        const double var_f_VDDR__Vm = var_I_VDDR__Vm; // voltage_units
        const double var_f_VDDR__f_inf_VDDR = 1.0 / (1.0 + exp((var_f_VDDR__Vm + 66.0) / 6.0)); // dimensionless
        const double var_f_VDDR__T_correction_Ca = var_I_VDDR__T_correction_Ca; // dimensionless
        const double var_f_VDDR__tau_f_VDDR = var_f_VDDR__T_correction_Ca * 0.040000000000000001; // time_units
        const double var_f_VDDR__f_VDDR = var_I_VDDR__f_VDDR; // dimensionless
        const double var_f_VDDR__d_f_VDDR_d_Time__time = (var_f_VDDR__f_inf_VDDR - var_f_VDDR__f_VDDR) / var_f_VDDR__tau_f_VDDR; // 'per second'
        const double var_I_VDDR__f_VDDR__d_f_VDDR_d_Time__time = var_f_VDDR__d_f_VDDR_d_Time__time; // ___units_31
        const double var_ICC_Membrane__f_VDDR__d_f_VDDR_d_Time__time = var_I_VDDR__f_VDDR__d_f_VDDR_d_Time__time; // ___units_31
        const double var_d_CaCl__d_CaCl = var_I_CaCl__d_CaCl; // dimensionless
        const double var_I_CaCl__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
        const double var_d_CaCl__Ca_i = var_I_CaCl__Ca_i; // millimolar
        const double var_d_CaCl__d_inf_CaCl = 1.0 / (1.0 + pow(0.00013999999999999999 / var_d_CaCl__Ca_i, 3.0)); // dimensionless
        const double var_d_CaCl__tau_d_CaCl = 0.029999999999999999; // time_units
        const double var_d_CaCl__d_d_CaCl_d_Time__time = (var_d_CaCl__d_inf_CaCl - var_d_CaCl__d_CaCl) / var_d_CaCl__tau_d_CaCl; // 'per second'
        const double var_I_CaCl__d_CaCl__d_d_CaCl_d_Time__time = var_d_CaCl__d_d_CaCl_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_CaCl__d_d_CaCl_d_Time__time = var_I_CaCl__d_CaCl__d_d_CaCl_d_Time__time; // ___units_31
        const double var_d_ERG__Vm = var_I_ERG__Vm; // voltage_units
        const double var_d_ERG__d_inf_ERG = 0.20000000000000001 + (0.80000000000000004 / (1.0 + exp((var_d_ERG__Vm + 20.0) / (-1.8)))); // dimensionless
        const double var_d_ERG__d_ERG = var_I_ERG__d_ERG; // dimensionless
        const double var_I_ERG__T_correction_K = var_ICC_Membrane__T_correction_K; // dimensionless
        const double var_d_ERG__T_correction_K = var_I_ERG__T_correction_K; // dimensionless
        const double var_d_ERG__tau_d_ERG = var_d_ERG__T_correction_K * 0.0030000000000000001; // time_units
        const double var_d_ERG__d_d_ERG_d_Time__time = (var_d_ERG__d_inf_ERG - var_d_ERG__d_ERG) / var_d_ERG__tau_d_ERG; // 'per second'
        const double var_I_ERG__d_ERG__d_d_ERG_d_Time__time = var_d_ERG__d_d_ERG_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_ERG__d_d_ERG_d_Time__time = var_I_ERG__d_ERG__d_d_ERG_d_Time__time; // ___units_31
        const double var_d_kv11__d_kv11 = var_I_kv11__d_kv11; // dimensionless
        const double var_I_kv11__T_correction_K = var_ICC_Membrane__T_correction_K; // dimensionless
        const double var_d_kv11__T_correction_K = var_I_kv11__T_correction_K; // dimensionless
        const double var_d_kv11__tau_d_kv11 = var_d_kv11__T_correction_K * 0.0050000000000000001; // time_units
        const double var_d_kv11__Vm = var_I_kv11__Vm; // voltage_units
        const double var_d_kv11__d_inf_kv11 = 1.0 / (1.0 + exp((var_d_kv11__Vm + 25.0) / (-7.7000000000000002))); // dimensionless
        const double var_d_kv11__d_d_kv11_d_Time__time = (var_d_kv11__d_inf_kv11 - var_d_kv11__d_kv11) / var_d_kv11__tau_d_kv11; // 'per second'
        const double var_I_kv11__d_kv11__d_d_kv11_d_Time__time = var_d_kv11__d_d_kv11_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_kv11__d_d_kv11_d_Time__time = var_I_kv11__d_kv11__d_d_kv11_d_Time__time; // ___units_31
        const double var_f_kv11__Vm = var_I_kv11__Vm; // voltage_units
        const double var_f_kv11__f_inf_kv11 = 0.5 + (0.5 / (1.0 + exp((var_f_kv11__Vm + 44.799999999999997) / 4.4000000000000004))); // dimensionless
        const double var_f_kv11__f_kv11 = var_I_kv11__f_kv11; // dimensionless
        const double var_f_kv11__T_correction_K = var_I_kv11__T_correction_K; // dimensionless
        const double var_f_kv11__tau_f_kv11 = var_f_kv11__T_correction_K * 0.0050000000000000001; // time_units
        const double var_f_kv11__d_f_kv11_d_Time__time = (var_f_kv11__f_inf_kv11 - var_f_kv11__f_kv11) / var_f_kv11__tau_f_kv11; // 'per second'
        const double var_I_kv11__f_kv11__d_f_kv11_d_Time__time = var_f_kv11__d_f_kv11_d_Time__time; // ___units_31
        const double var_ICC_Membrane__f_kv11__d_f_kv11_d_Time__time = var_I_kv11__f_kv11__d_f_kv11_d_Time__time; // ___units_31
        const double var_d_Na__Vm = var_I_Na__Vm; // voltage_units
        const double var_d_Na__d_inf_Na = 1.0 / (1.0 + exp((var_d_Na__Vm + 47.0) / (-4.7999999999999998))); // dimensionless
        const double var_d_Na__d_Na = var_I_Na__d_Na; // dimensionless
        const double var_I_Na__T_correction_Na = var_ICC_Membrane__T_correction_Na; // dimensionless
        const double var_d_Na__T_correction_Na = var_I_Na__T_correction_Na; // dimensionless
        const double var_d_Na__tau_d_Na = var_d_Na__T_correction_Na * 0.0030000000000000001; // time_units
        const double var_d_Na__d_d_Na_d_Time__time = (var_d_Na__d_inf_Na - var_d_Na__d_Na) / var_d_Na__tau_d_Na; // 'per second'
        const double var_I_Na__d_Na__d_d_Na_d_Time__time = var_d_Na__d_d_Na_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_Na__d_d_Na_d_Time__time = var_I_Na__d_Na__d_d_Na_d_Time__time; // ___units_31
        const double var_f_Na__f_Na = var_I_Na__f_Na; // dimensionless
        const double var_f_Na__Vm = var_I_Na__Vm; // voltage_units
        const double var_f_Na__f_inf_Na = 1.0 / (1.0 + exp((var_f_Na__Vm + 78.0) / 7.0)); // dimensionless
        const double var_f_Na__T_correction_Na = var_I_Na__T_correction_Na; // dimensionless
        const double var_f_Na__tau_f_Na = var_f_Na__T_correction_Na * 0.0016000000000000001; // time_units
        const double var_f_Na__d_f_Na_d_Time__time = (var_f_Na__f_inf_Na - var_f_Na__f_Na) / var_f_Na__tau_f_Na; // 'per second'
        const double var_I_Na__f_Na__d_f_Na_d_Time__time = var_f_Na__d_f_Na_d_Time__time; // ___units_31
        const double var_ICC_Membrane__f_Na__d_f_Na_d_Time__time = var_I_Na__f_Na__d_f_Na_d_Time__time; // ___units_31
        const double var_I_NSCC__Ca_PU = var_ICC_Membrane__Ca_PU; // millimolar
        const double var_d_NSCC__Ca_PU = var_I_NSCC__Ca_PU; // millimolar
        const double var_d_NSCC__d_inf_NSCC = 1.0 / (1.0 + pow(7.4499999999999995e-05 / var_d_NSCC__Ca_PU, -85.0)); // dimensionless
        const double var_d_NSCC__d_NSCC = var_I_NSCC__d_NSCC; // dimensionless
        const double var_d_NSCC__tau_d_NSCC = 0.34999999999999998; // time_units
        const double var_d_NSCC__d_d_NSCC_d_Time__time = (var_d_NSCC__d_inf_NSCC - var_d_NSCC__d_NSCC) / var_d_NSCC__tau_d_NSCC; // 'per second'
        const double var_I_NSCC__d_NSCC__d_d_NSCC_d_Time__time = var_d_NSCC__d_d_NSCC_d_Time__time; // ___units_31
        const double var_ICC_Membrane__d_NSCC__d_d_NSCC_d_Time__time = var_I_NSCC__d_NSCC__d_d_NSCC_d_Time__time; // ___units_31
        const double var_PU_unit__K_Ca = 0.0030000000000000001; // millimolar
        const double var_ICC_Membrane__deltaPsi = var_chaste_interface__PU_unit__deltaPsi; // voltage_units
        const double var_PU_unit__deltaPsi = var_ICC_Membrane__deltaPsi; // voltage_units
        const double var_PU_unit__FoRT = var_ICC_Membrane__FoRT; // Inverse_Voltage_units
        const double var_PU_unit__Jmax_NaCa = 0.050000000000000003; // millimolar_per_second
        const double var_PU_unit__n = 2.0; // dimensionless
        const double var_PU_unit__Na_i = var_ICC_Membrane__Na_i; // millimolar
        const double var_PU_unit__K_Na = 9.4000000000000004; // millimolar
        const double var_ICC_Membrane__Ca_m = var_chaste_interface__PU_unit__Ca_m; // millimolar
        const double var_PU_unit__Ca_m = var_ICC_Membrane__Ca_m; // millimolar
        const double var_PU_unit__b = 0.5; // dimensionless
        const double var_PU_unit__deltaPsi_star = 91.0; // voltage_units
        const double var_PU_unit__J_NaCa = (var_PU_unit__Jmax_NaCa * exp(var_PU_unit__b * var_PU_unit__FoRT * (var_PU_unit__deltaPsi - var_PU_unit__deltaPsi_star))) / ((1.0 + pow(var_PU_unit__K_Na / var_PU_unit__Na_i, var_PU_unit__n)) * (1.0 + (var_PU_unit__K_Ca / var_PU_unit__Ca_m))); // millimolar_per_second
        const double var_PU_unit__V_cyto = var_ICC_Membrane__V_cyto; // volume_units
        const double var_PU_unit__Jmax_uni = 5000.0; // rate_constants_units
        const double var_PU_unit__K_trans = 0.0060000000000000001; // millimolar
        const double var_PU_unit__L = 50.0; // dimensionless
        const double var_PU_unit__na = 2.7999999999999998; // dimensionless
        const double var_PU_unit__K_act = 0.00038000000000000002; // millimolar
        const double var_PU_unit__conc = 0.001; // millimolar
        const double var_PU_unit__MWC = (((var_PU_unit__conc * var_PU_unit__Ca_PU) / var_PU_unit__K_trans) * pow(1.0 + (var_PU_unit__Ca_PU / var_PU_unit__K_trans), 3.0)) / (pow(1.0 + (var_PU_unit__Ca_PU / var_PU_unit__K_trans), 4.0) + (var_PU_unit__L / pow(1.0 + (var_PU_unit__Ca_PU / var_PU_unit__K_act), var_PU_unit__na))); // millimolar
        const double var_PU_unit__J_uni = (var_PU_unit__Jmax_uni * (var_PU_unit__MWC - (var_PU_unit__Ca_m * exp((-2.0) * var_PU_unit__FoRT * (var_PU_unit__deltaPsi - var_PU_unit__deltaPsi_star)))) * 2.0 * var_PU_unit__FoRT * (var_PU_unit__deltaPsi - var_PU_unit__deltaPsi_star)) / (1.0 - exp((-2.0) * var_PU_unit__FoRT * (var_PU_unit__deltaPsi - var_PU_unit__deltaPsi_star))); // millimolar_per_second
        const double var_PU_unit__Vol = var_ICC_Membrane__Vol; // volume_units
        const double var_PU_unit__P_PU = 0.001; // dimensionless
        const double var_PU_unit__V_PU = var_PU_unit__Vol * var_PU_unit__P_PU; // volume_units
        const double var_PU_unit__P_mito = 0.12870999999999999; // dimensionless
        const double var_PU_unit__V_MITO = var_PU_unit__Vol * var_PU_unit__P_mito; // volume_units
        const double var_PU_unit__Jmax_serca = 1.8332999999999999; // millimolar_per_second
        const double var_PU_unit__k_serca = 0.00042000000000000002; // millimolar
        const double var_PU_unit__J_SERCA = (var_PU_unit__Jmax_serca * pow(var_PU_unit__Ca_PU, 2.0)) / (pow(var_PU_unit__k_serca, 2.0) + pow(var_PU_unit__Ca_PU, 2.0)); // millimolar_per_second
        const double var_PU_unit__P_ER = 0.10000000000000001; // dimensionless
        const double var_PU_unit__V_ER = var_PU_unit__Vol * var_PU_unit__P_ER; // volume_units
        const double var_ICC_Membrane__Ca_ER = var_chaste_interface__PU_unit__Ca_ER; // millimolar
        const double var_PU_unit__Ca_ER = var_ICC_Membrane__Ca_ER; // millimolar
        const double var_PU_unit__d_IP3 = 0.00025000000000000001; // millimolar
        const double var_PU_unit__IP3 = 0.00059999999999999995; // millimolar
        const double var_PU_unit__d_ACT = 0.001; // millimolar
        const double var_PU_unit__Jmax_IP3 = 50000.0; // rate_constants_units
        const double var_ICC_Membrane__h = var_chaste_interface__PU_unit__h; // dimensionless
        const double var_PU_unit__h = var_ICC_Membrane__h; // dimensionless
        const double var_PU_unit__J_ERleak = 1.6666669999999999; // rate_constants_units
        const double var_PU_unit__J_ERout = ((var_PU_unit__Jmax_IP3 * pow(var_PU_unit__IP3 / (var_PU_unit__IP3 + var_PU_unit__d_IP3), 3.0) * pow(var_PU_unit__Ca_PU / (var_PU_unit__Ca_PU + var_PU_unit__d_ACT), 3.0) * pow(var_PU_unit__h, 3.0)) + var_PU_unit__J_ERleak) * (var_PU_unit__Ca_ER - var_PU_unit__Ca_PU); // millimolar_per_second
        const double var_PU_unit__fc = var_ICC_Membrane__fc; // dimensionless
        const double var_PU_unit__d_Ca_PU_d_Time__time = var_PU_unit__fc * ((((var_PU_unit__J_NaCa - var_PU_unit__J_uni) * var_PU_unit__V_MITO) / var_PU_unit__V_PU) + (((var_PU_unit__J_ERout - var_PU_unit__J_SERCA) * var_PU_unit__V_ER) / var_PU_unit__V_PU) + (((-1.0) * var_PU_unit__J_leak * var_PU_unit__V_cyto) / var_PU_unit__V_PU)); // 'millimole per litre per second'
        const double var_ICC_Membrane__PU_unit__d_Ca_PU_d_Time__time = var_PU_unit__d_Ca_PU_d_Time__time; // ___units_23
        const double var_PU_unit__fm = 0.00029999999999999997; // dimensionless
        const double var_PU_unit__d_Ca_m_d_Time__time = var_PU_unit__fm * (var_PU_unit__J_uni - var_PU_unit__J_NaCa); // 'millimole per litre per second'
        const double var_ICC_Membrane__PU_unit__d_Ca_m_d_Time__time = var_PU_unit__d_Ca_m_d_Time__time; // ___units_23
        const double var_PU_unit__fe = 0.01; // dimensionless
        const double var_PU_unit__d_Ca_ER_d_Time__time = var_PU_unit__fe * (var_PU_unit__J_SERCA - var_PU_unit__J_ERout); // 'millimole per litre per second'
        const double var_ICC_Membrane__PU_unit__d_Ca_ER_d_Time__time = var_PU_unit__d_Ca_ER_d_Time__time; // ___units_23
        const double var_PU_unit__Jmax_ANT = 15.0; // millimolar_per_second
        const double var_PU_unit__frac = 0.5; // dimensionless
        const double var_ICC_Membrane__ADP_i = var_chaste_interface__PU_unit__ADP_i; // millimolar
        const double var_PU_unit__ADP_i = var_ICC_Membrane__ADP_i; // millimolar
        const double var_PU_unit__ADP_ifree = 0.29999999999999999 * var_PU_unit__ADP_i; // millimolar
        const double var_PU_unit__ADP3_i = 0.45000000000000001 * var_PU_unit__ADP_ifree; // millimolar
        const double var_ICC_Membrane__ADP_m = var_chaste_interface__PU_unit__ADP_m; // millimolar
        const double var_PU_unit__ADP_m = var_ICC_Membrane__ADP_m; // millimolar
        const double var_PU_unit__ADP_mfree = 0.80000000000000004 * var_PU_unit__ADP_m; // millimolar
        const double var_PU_unit__ADP3_m = 0.45000000000000001 * var_PU_unit__ADP_mfree; // millimolar
        const double var_PU_unit__total_ANP_i = 2.0; // millimolar
        const double var_PU_unit__ATP_i = var_PU_unit__total_ANP_i - var_PU_unit__ADP_i; // millimolar
        const double var_PU_unit__ATP4_i = 0.050000000000000003 * var_PU_unit__ATP_i; // millimolar
        const double var_PU_unit__total_ANP_m = 12.0; // millimolar
        const double var_PU_unit__ATP_m = var_PU_unit__total_ANP_m - var_PU_unit__ADP_m; // millimolar
        const double var_PU_unit__ATP4_m = 0.050000000000000003 * var_PU_unit__ATP_m; // millimolar
        const double var_PU_unit__J_ANT = (var_PU_unit__Jmax_ANT * (1.0 - (((var_PU_unit__ATP4_i * var_PU_unit__ADP3_m) / (var_PU_unit__ADP3_i * var_PU_unit__ATP4_m)) * exp((-1.0) * var_PU_unit__FoRT * var_PU_unit__deltaPsi)))) / ((1.0 + ((var_PU_unit__ATP4_i / var_PU_unit__ADP3_i) * exp((-1.0) * var_PU_unit__frac * var_PU_unit__FoRT * var_PU_unit__deltaPsi))) * (1.0 + (var_PU_unit__ADP3_m / var_PU_unit__ATP4_m))); // millimolar_per_second
        const double var_PU_unit__J_red_basal = 0.33329999999999999; // millimolar_per_second
        const double var_PU_unit__u1 = 15.0; // dimensionless
        const double var_PU_unit__u2 = 1.1000000000000001; // dimensionless
        const double var_PU_unit__KCa_PDH = 5.0000000000000002e-05; // millimolar
        const double var_PU_unit__f_PDHa = 1.0 / (1.0 + (var_PU_unit__u2 * (1.0 + (var_PU_unit__u1 / pow(1.0 + (var_PU_unit__Ca_m / var_PU_unit__KCa_PDH), 2.0))))); // dimensionless
        const double var_PU_unit__beta_max = 2.0550000000000002; // rate_constants_units
        const double var_PU_unit__Glc = 1.0; // millimolar
        const double var_PU_unit__beta1 = 1.6599999999999999; // per_millimolar
        const double var_PU_unit__beta2 = 0.024899999999999999; // per_millimolar
        const double var_PU_unit__beta3 = 4.0; // per_millimolar
        const double var_PU_unit__beta4 = 2.8300000000000001; // per_millimolar
        const double var_PU_unit__beta5 = 1.3; // per_millimolar
        const double var_PU_unit__beta6 = 2.6600000000000001; // per_millimolar
        const double var_PU_unit__beta7 = 0.16; // per_millimolar
        const double var_PU_unit__J_glyTotal = (var_PU_unit__beta_max * (1.0 + (var_PU_unit__beta1 * var_PU_unit__Glc)) * var_PU_unit__beta2 * var_PU_unit__Glc * var_PU_unit__ATP_i) / (1.0 + (var_PU_unit__beta3 * var_PU_unit__ATP_i) + ((1.0 + (var_PU_unit__beta4 * var_PU_unit__ATP_i)) * var_PU_unit__beta5 * var_PU_unit__Glc) + ((1.0 + (var_PU_unit__beta6 * var_PU_unit__ATP_i)) * var_PU_unit__beta7 * var_PU_unit__Glc)); // millimolar_per_second
        const double var_PU_unit__J_pTCA = (var_PU_unit__J_red_basal / 3.0) + (0.83999999999999997 * var_PU_unit__f_PDHa * var_PU_unit__J_glyTotal); // millimolar_per_second
        const double var_PU_unit__pa = 1.6560000000000001e-05; // rate_constants_units
        const double var_PU_unit__deltaPsi_B = 50.0; // voltage_units
        const double var_PU_unit__rho_F1 = 0.69999999999999996; // millimolar
        const double var_PU_unit__Pi_m = 20.0; // millimolar
        const double var_PU_unit__RToF = var_ICC_Membrane__RToF; // voltage_units
        const double var_PU_unit__K_F1 = 1710000000.0; // millimolar
        const double var_PU_unit__A_F1 = var_PU_unit__RToF * log((var_PU_unit__K_F1 * var_PU_unit__ATP_m) / (var_PU_unit__ADP_mfree * var_PU_unit__Pi_m)); // voltage_units
        const double var_PU_unit__pc1 = 9.6509999999999997e-14; // rate_constants_units
        const double var_PU_unit__pc2 = 4.845e-19; // rate_constants_units
        const double var_PU_unit__p3 = 6.6500000000000004e-15; // dimensionless
        const double var_PU_unit__p2 = 7.7390000000000001e-07; // dimensionless
        const double var_PU_unit__p1 = 1.3459999999999999e-08; // dimensionless
        const double var_PU_unit__deltapH =  -0.40000000000000002; // dimensionless
        const double var_PU_unit__J_pF1 = (var_PU_unit__rho_F1 * (-1.0) * ((((var_PU_unit__pa * pow(10.0, 3.0 * var_PU_unit__deltapH)) + (var_PU_unit__pc1 * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi_B))) * exp(var_PU_unit__FoRT * var_PU_unit__A_F1)) + ((-1.0) * var_PU_unit__pa * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi)) + (var_PU_unit__pc2 * exp(var_PU_unit__FoRT * var_PU_unit__A_F1) * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi)))) / (((1.0 + (var_PU_unit__p1 * exp(var_PU_unit__FoRT * var_PU_unit__A_F1))) * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi_B)) + ((var_PU_unit__p2 + (var_PU_unit__p3 * exp(var_PU_unit__FoRT * var_PU_unit__A_F1))) * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi))); // millimolar_per_second
        const double var_PU_unit__d_ADP_m_d_Time__time = var_PU_unit__J_ANT + ((-1.0) * var_PU_unit__J_pTCA) + ((-1.0) * var_PU_unit__J_pF1); // 'millimole per litre per second'
        const double var_ICC_Membrane__PU_unit__d_ADP_m_d_Time__time = var_PU_unit__d_ADP_m_d_Time__time; // ___units_23
        const double var_PU_unit__J_pGly = 0.14999999999999999 * var_PU_unit__J_glyTotal; // millimolar_per_second
        const double var_PU_unit__K_Glc = 8.6999999999999993; // millimolar
        const double var_PU_unit__J_hyd_max = 0.037624999999999999; // millimolar_per_second
        const double var_PU_unit__nhyd = 2.7000000000000002; // dimensionless
        const double var_PU_unit__J_hydSS = var_PU_unit__J_hyd_max / (1.0 + pow(var_PU_unit__K_Glc / var_PU_unit__Glc, var_PU_unit__nhyd)); // millimolar_per_second
        const double var_PU_unit__K_hyd = 0.051249999999999997; // rate_constants_units
        const double var_PU_unit__J_hyd = (var_PU_unit__K_hyd * var_PU_unit__ATP_i) + var_PU_unit__J_hydSS; // millimolar_per_second
        const double var_PU_unit__d_ADP_i_d_Time__time = (((-1.0) * var_PU_unit__J_ANT * var_PU_unit__V_MITO) / var_PU_unit__V_cyto) + var_PU_unit__J_hyd + ((-1.0) * var_PU_unit__J_pGly); // 'millimole per litre per second'
        const double var_ICC_Membrane__PU_unit__d_ADP_i_d_Time__time = var_PU_unit__d_ADP_i_d_Time__time; // ___units_23
        const double var_PU_unit__J_red = var_PU_unit__J_red_basal + (6.3944000000000001 * var_PU_unit__f_PDHa * var_PU_unit__J_glyTotal); // millimolar_per_second
        const double var_ICC_Membrane__NADH_m = var_chaste_interface__PU_unit__NADH_m; // millimolar
        const double var_PU_unit__NADH_m = var_ICC_Membrane__NADH_m; // millimolar
        const double var_PU_unit__K_res = 1.35e+18; // dimensionless
        const double var_PU_unit__total_NAD_m = 8.0; // millimolar
        const double var_PU_unit__NAD_m = var_PU_unit__total_NAD_m - var_PU_unit__NADH_m; // millimolar
        const double var_PU_unit__A_res = var_PU_unit__RToF * log((var_PU_unit__K_res * sqrt(var_PU_unit__NADH_m)) / sqrt(var_PU_unit__NAD_m)); // voltage_units
        const double var_PU_unit__rho_res = 0.40000000000000002; // millimolar
        const double var_PU_unit__r1 = 2.0769999999999998e-18; // dimensionless
        const double var_PU_unit__r3 = 1.059e-26; // dimensionless
        const double var_PU_unit__r2 = 1.728e-09; // dimensionless
        const double var_PU_unit__rc2 = 8.6320000000000006e-27; // rate_constants_units
        const double var_PU_unit__rc1 = 2.6560000000000001e-19; // rate_constants_units
        const double var_PU_unit__ra = 6.3939999999999998e-10; // rate_constants_units
        const double var_PU_unit__g = 0.84999999999999998; // dimensionless
        const double var_PU_unit__J_o = (var_PU_unit__rho_res * 0.5 * ((((var_PU_unit__ra * pow(10.0, 6.0 * var_PU_unit__deltapH)) + (var_PU_unit__rc1 * exp(6.0 * var_PU_unit__deltaPsi_B * var_PU_unit__FoRT))) * exp(var_PU_unit__A_res * var_PU_unit__FoRT)) + ((-1.0) * var_PU_unit__ra * exp(var_PU_unit__g * 6.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi)) + (var_PU_unit__rc2 * exp(var_PU_unit__FoRT * var_PU_unit__A_res) * exp(var_PU_unit__FoRT * var_PU_unit__deltaPsi * 6.0 * var_PU_unit__g)))) / (((1.0 + (var_PU_unit__r1 * exp(var_PU_unit__FoRT * var_PU_unit__A_res))) * exp(var_PU_unit__FoRT * var_PU_unit__deltaPsi_B * 6.0)) + ((var_PU_unit__r2 + (var_PU_unit__r3 * exp(var_PU_unit__FoRT * var_PU_unit__A_res))) * exp(var_PU_unit__FoRT * var_PU_unit__deltaPsi * var_PU_unit__g * 6.0))); // millimolar_per_second
        const double var_PU_unit__d_NADH_m_d_Time__time = var_PU_unit__J_red - var_PU_unit__J_o; // 'millimole per litre per second'
        const double var_ICC_Membrane__PU_unit__d_NADH_m_d_Time__time = var_PU_unit__d_NADH_m_d_Time__time; // ___units_23
        const double var_PU_unit__d_INH = 0.0014; // millimolar
        const double var_PU_unit__tauh = 4.0; // time_units
        const double var_PU_unit__d_h_d_Time__time = (1.0 * (var_PU_unit__d_INH - (var_PU_unit__h * (var_PU_unit__Ca_PU + var_PU_unit__d_INH)))) / var_PU_unit__tauh; // 'per second'
        const double var_ICC_Membrane__PU_unit__d_h_d_Time__time = var_PU_unit__d_h_d_Time__time; // ___units_31
        const double var_PU_unit__pb = 3.3729999999999998e-07; // rate_constants_units
        const double var_PU_unit__J_HF1 = ((-1.0) * var_PU_unit__rho_F1 * 3.0 * ((var_PU_unit__pa * pow(10.0, 3.0 * var_PU_unit__deltapH) * exp(var_PU_unit__FoRT * var_PU_unit__A_F1)) + (var_PU_unit__pb * pow(10.0, 3.0 * var_PU_unit__deltapH)) + ((-1.0) * (var_PU_unit__pa + var_PU_unit__pb) * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi)))) / (((1.0 + (var_PU_unit__p1 * exp(var_PU_unit__FoRT * var_PU_unit__A_F1))) * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi_B)) + ((var_PU_unit__p2 + (var_PU_unit__p3 * exp(var_PU_unit__FoRT * var_PU_unit__A_F1))) * exp(3.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi))); // millimolar_per_second
        const double var_PU_unit__rb = 1.762e-13; // rate_constants_units
        const double var_PU_unit__J_Hres = (var_PU_unit__rho_res * 3.9660000000000002 * ((var_PU_unit__ra * pow(10.0, 6.0 * var_PU_unit__deltapH) * exp(var_PU_unit__FoRT * var_PU_unit__A_res)) + (var_PU_unit__rb * pow(10.0, 6.0 * var_PU_unit__deltapH)) + ((-1.0) * (var_PU_unit__ra + var_PU_unit__rb) * exp(var_PU_unit__g * var_PU_unit__FoRT * var_PU_unit__deltaPsi * 6.0)))) / (((1.0 + (var_PU_unit__r1 * exp(var_PU_unit__FoRT * var_PU_unit__A_res))) * exp(6.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi_B)) + ((var_PU_unit__r2 + (var_PU_unit__r3 * exp(var_PU_unit__FoRT * var_PU_unit__A_res))) * exp(var_PU_unit__g * 6.0 * var_PU_unit__FoRT * var_PU_unit__deltaPsi))); // millimolar_per_second
        const double var_PU_unit__Cmito = 0.0069950000000000003; // millifarads
        const double var_PU_unit__F = var_ICC_Membrane__F; // F_units
        const double var_PU_unit__PMF = var_PU_unit__deltaPsi - (2.3029999999999999 * var_PU_unit__RToF * var_PU_unit__deltapH); // voltage_units
        const double var_PU_unit__g_H = 0.0033333; // millimolar_per_second_per_millivolt
        const double var_PU_unit__J_Hleak = var_PU_unit__g_H * var_PU_unit__PMF; // millimolar_per_second
        const double var_PU_unit__d_deltaPsi_d_Time__time = (((-1.0) * var_PU_unit__F * var_PU_unit__V_MITO * 1000000.0 * 1.0) / var_PU_unit__Cmito) * (var_PU_unit__J_Hleak + ((-1.0) * var_PU_unit__J_Hres) + var_PU_unit__J_ANT + var_PU_unit__J_HF1 + (2.0 * var_PU_unit__J_uni)); // 'millivolt per second'
        const double var_ICC_Membrane__PU_unit__d_deltaPsi_d_Time__time = var_PU_unit__d_deltaPsi_d_Time__time; // ___units_11
        const double var_chaste_interface__ICC_Membrane__d_Ca_i_d_Time__time_converter = var_ICC_Membrane__d_Ca_i_d_Time__time; // ___units_23
        const double var_chaste_interface__ICC_Membrane__d_Ca_i_d_Time__time = 0.001 * var_chaste_interface__ICC_Membrane__d_Ca_i_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__d_Ltype__d_d_Ltype_d_Time__time_converter = var_ICC_Membrane__d_Ltype__d_d_Ltype_d_Time__time; // ___units_31
        const double var_chaste_interface__d_Ltype__d_d_Ltype_d_Time__time = 0.001 * var_chaste_interface__d_Ltype__d_d_Ltype_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__f_Ltype__d_f_Ltype_d_Time__time_converter = var_ICC_Membrane__f_Ltype__d_f_Ltype_d_Time__time; // per_second
        const double var_chaste_interface__f_Ltype__d_f_Ltype_d_Time__time = 0.001 * var_chaste_interface__f_Ltype__d_f_Ltype_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__f_ca_Ltype__d_f_ca_Ltype_d_Time__time_converter = var_ICC_Membrane__f_ca_Ltype__d_f_ca_Ltype_d_Time__time; // per_second
        const double var_chaste_interface__f_ca_Ltype__d_f_ca_Ltype_d_Time__time = 0.001 * var_chaste_interface__f_ca_Ltype__d_f_ca_Ltype_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__d_VDDR__d_d_VDDR_d_Time__time_converter = var_ICC_Membrane__d_VDDR__d_d_VDDR_d_Time__time; // per_second
        const double var_chaste_interface__d_VDDR__d_d_VDDR_d_Time__time = 0.001 * var_chaste_interface__d_VDDR__d_d_VDDR_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__f_VDDR__d_f_VDDR_d_Time__time_converter = var_ICC_Membrane__f_VDDR__d_f_VDDR_d_Time__time; // per_second
        const double var_chaste_interface__f_VDDR__d_f_VDDR_d_Time__time = 0.001 * var_chaste_interface__f_VDDR__d_f_VDDR_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__d_CaCl__d_d_CaCl_d_Time__time_converter = var_ICC_Membrane__d_CaCl__d_d_CaCl_d_Time__time; // per_second
        const double var_chaste_interface__d_CaCl__d_d_CaCl_d_Time__time = 0.001 * var_chaste_interface__d_CaCl__d_d_CaCl_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__d_ERG__d_d_ERG_d_Time__time_converter = var_ICC_Membrane__d_ERG__d_d_ERG_d_Time__time; // per_second
        const double var_chaste_interface__d_ERG__d_d_ERG_d_Time__time = 0.001 * var_chaste_interface__d_ERG__d_d_ERG_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__d_kv11__d_d_kv11_d_Time__time_converter = var_ICC_Membrane__d_kv11__d_d_kv11_d_Time__time; // per_second
        const double var_chaste_interface__d_kv11__d_d_kv11_d_Time__time = 0.001 * var_chaste_interface__d_kv11__d_d_kv11_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__f_kv11__d_f_kv11_d_Time__time_converter = var_ICC_Membrane__f_kv11__d_f_kv11_d_Time__time; // per_second
        const double var_chaste_interface__f_kv11__d_f_kv11_d_Time__time = 0.001 * var_chaste_interface__f_kv11__d_f_kv11_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__d_Na__d_d_Na_d_Time__time_converter = var_ICC_Membrane__d_Na__d_d_Na_d_Time__time; // per_second
        const double var_chaste_interface__d_Na__d_d_Na_d_Time__time = 0.001 * var_chaste_interface__d_Na__d_d_Na_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__f_Na__d_f_Na_d_Time__time_converter = var_ICC_Membrane__f_Na__d_f_Na_d_Time__time; // per_second
        const double var_chaste_interface__f_Na__d_f_Na_d_Time__time = 0.001 * var_chaste_interface__f_Na__d_f_Na_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__d_NSCC__d_d_NSCC_d_Time__time_converter = var_ICC_Membrane__d_NSCC__d_d_NSCC_d_Time__time; // per_second
        const double var_chaste_interface__d_NSCC__d_d_NSCC_d_Time__time = 0.001 * var_chaste_interface__d_NSCC__d_d_NSCC_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__PU_unit__d_Ca_PU_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_Ca_PU_d_Time__time; // millimole_per_litre_per_second
        const double var_chaste_interface__PU_unit__d_Ca_PU_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_Ca_PU_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__PU_unit__d_Ca_m_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_Ca_m_d_Time__time; // millimole_per_litre_per_second
        const double var_chaste_interface__PU_unit__d_Ca_m_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_Ca_m_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__PU_unit__d_Ca_ER_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_Ca_ER_d_Time__time; // millimole_per_litre_per_second
        const double var_chaste_interface__PU_unit__d_Ca_ER_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_Ca_ER_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__PU_unit__d_ADP_m_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_ADP_m_d_Time__time; // millimole_per_litre_per_second
        const double var_chaste_interface__PU_unit__d_ADP_m_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_ADP_m_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__PU_unit__d_ADP_i_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_ADP_i_d_Time__time; // millimole_per_litre_per_second
        const double var_chaste_interface__PU_unit__d_ADP_i_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_ADP_i_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__PU_unit__d_NADH_m_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_NADH_m_d_Time__time; // millimole_per_litre_per_second
        const double var_chaste_interface__PU_unit__d_NADH_m_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_NADH_m_d_Time__time_converter; // 'millimolar per millisecond'
        const double var_chaste_interface__PU_unit__d_h_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_h_d_Time__time; // per_second
        const double var_chaste_interface__PU_unit__d_h_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_h_d_Time__time_converter; // 'per millisecond'
        const double var_chaste_interface__PU_unit__d_deltaPsi_d_Time__time_converter = var_ICC_Membrane__PU_unit__d_deltaPsi_d_Time__time; // millivolt_per_second
        const double var_chaste_interface__PU_unit__d_deltaPsi_d_Time__time = 0.001 * var_chaste_interface__PU_unit__d_deltaPsi_d_Time__time_converter; // 'voltage_units per millisecond'
        const double d_dt_chaste_interface__ICC_Membrane__Ca_i = var_chaste_interface__ICC_Membrane__d_Ca_i_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__d_Ltype__d_Ltype = var_chaste_interface__d_Ltype__d_d_Ltype_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__f_Ltype__f_Ltype = var_chaste_interface__f_Ltype__d_f_Ltype_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__f_ca_Ltype__f_ca_Ltype = var_chaste_interface__f_ca_Ltype__d_f_ca_Ltype_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__d_VDDR__d_VDDR = var_chaste_interface__d_VDDR__d_d_VDDR_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__f_VDDR__f_VDDR = var_chaste_interface__f_VDDR__d_f_VDDR_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__d_CaCl__d_CaCl = var_chaste_interface__d_CaCl__d_d_CaCl_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__d_ERG__d_ERG = var_chaste_interface__d_ERG__d_d_ERG_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__d_kv11__d_kv11 = var_chaste_interface__d_kv11__d_d_kv11_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__f_kv11__f_kv11 = var_chaste_interface__f_kv11__d_f_kv11_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__d_Na__d_Na = var_chaste_interface__d_Na__d_d_Na_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__f_Na__f_Na = var_chaste_interface__f_Na__d_f_Na_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__d_NSCC__d_NSCC = var_chaste_interface__d_NSCC__d_d_NSCC_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__PU_unit__Ca_PU = var_chaste_interface__PU_unit__d_Ca_PU_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__PU_unit__Ca_m = var_chaste_interface__PU_unit__d_Ca_m_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__PU_unit__Ca_ER = var_chaste_interface__PU_unit__d_Ca_ER_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__PU_unit__ADP_m = var_chaste_interface__PU_unit__d_ADP_m_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__PU_unit__ADP_i = var_chaste_interface__PU_unit__d_ADP_i_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__PU_unit__NADH_m = var_chaste_interface__PU_unit__d_NADH_m_d_Time__time; // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__PU_unit__h = var_chaste_interface__PU_unit__d_h_d_Time__time; // 'per millisecond'
        const double d_dt_chaste_interface__PU_unit__deltaPsi = var_chaste_interface__PU_unit__d_deltaPsi_d_Time__time; // 'millivolt per millisecond'
        
        if (mSetVoltageDerivativeToZero)
        {
            d_dt_chaste_interface__ICC_Membrane__Vm = 0.0;
        }
        else
        {
            const double var_Environment__Na_o = 137.0; // millimolar
            const double var_Environment__K_o = 7.0; // millimolar
            const double var_Environment__Cl_o = 134.0; // millimolar
            const double var_Environment__T_correction_BK = 1.1000000000000001 * (var_Environment__T - var_Environment__T_exp); // conductance_units
            const double var_ICC_Membrane__Cm = 0.025000000000000001; // capacitance_units
            const double var_ICC_Membrane__K_i = 120.0; // millimolar
            const double var_ICC_Membrane__Cl_i = 88.0; // millimolar
            const double var_ICC_Membrane__Na_o = var_Environment__Na_o; // millimolar
            const double var_ICC_Membrane__K_o = var_Environment__K_o; // millimolar
            const double var_ICC_Membrane__Cl_o = var_Environment__Cl_o; // millimolar
            const double var_ICC_Membrane__T_correction_BK = var_Environment__T_correction_BK; // conductance_units
            const double var_I_Na__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_Na__Na_i = var_ICC_Membrane__Na_i; // millimolar
            const double var_I_Na__Na_o = var_ICC_Membrane__Na_o; // millimolar
            const double var_I_Na__E_Na = var_I_Na__RToF * log(var_I_Na__Na_o / var_I_Na__Na_i); // voltage_units
            const double var_I_Na__G_max_Na = 20.0; // conductance_units
            const double var_I_Na__I_Na = var_I_Na__G_max_Na * var_I_Na__f_Na * var_I_Na__d_Na * (var_I_Na__Vm - var_I_Na__E_Na); // current_units
            const double var_ICC_Membrane__I_Na = var_I_Na__I_Na; // current_units
            const double var_I_kv11__G_max_kv11 = 6.2999999999999998; // conductance_units
            const double var_I_kv11__K_i = var_ICC_Membrane__K_i; // millimolar
            const double var_I_kv11__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_kv11__K_o = var_ICC_Membrane__K_o; // millimolar
            const double var_I_kv11__E_K = var_I_kv11__RToF * log(var_I_kv11__K_o / var_I_kv11__K_i); // voltage_units
            const double var_I_kv11__I_kv11 = var_I_kv11__G_max_kv11 * var_I_kv11__f_kv11 * var_I_kv11__d_kv11 * (var_I_kv11__Vm - var_I_kv11__E_K); // current_units
            const double var_ICC_Membrane__I_kv11 = var_I_kv11__I_kv11; // current_units
            const double var_I_BK__Vm = var_ICC_Membrane__Vm; // voltage_units
            const double var_I_BK__T_correction_BK = var_ICC_Membrane__T_correction_BK; // conductance_units
            const double var_I_BK__G_max_BK = 23.0; // conductance_units
            const double var_I_BK__K_i = var_ICC_Membrane__K_i; // millimolar
            const double var_I_BK__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_BK__K_o = var_ICC_Membrane__K_o; // millimolar
            const double var_I_BK__E_K = var_I_BK__RToF * log(var_I_BK__K_o / var_I_BK__K_i); // voltage_units
            const double var_I_BK__Ca_i = var_ICC_Membrane__Ca_i; // millimolar
            const double var_d_BK__Ca_i = var_I_BK__Ca_i; // millimolar
            const double var_d_BK__Vm = var_I_BK__Vm; // voltage_units
            const double var_d_BK__d_BK = 1.0 / (1.0 + exp((var_d_BK__Vm / (-17.0)) - (2.0 * log(var_d_BK__Ca_i / 0.001)))); // dimensionless
            const double var_I_BK__d_BK = var_d_BK__d_BK; // dimensionless
            const double var_I_BK__I_BK = (var_I_BK__G_max_BK + var_I_BK__T_correction_BK) * var_I_BK__d_BK * (var_I_BK__Vm - var_I_BK__E_K); // current_units
            const double var_ICC_Membrane__I_BK = var_I_BK__I_BK; // current_units
            const double var_I_ERG__G_max_ERG = 2.5; // conductance_units
            const double var_I_ERG__K_o = var_ICC_Membrane__K_o; // millimolar
            const double var_I_ERG__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_ERG__K_i = var_ICC_Membrane__K_i; // millimolar
            const double var_I_ERG__E_K = var_I_ERG__RToF * log(var_I_ERG__K_o / var_I_ERG__K_i); // voltage_units
            const double var_I_ERG__I_ERG = var_I_ERG__G_max_ERG * var_I_ERG__d_ERG * (var_I_ERG__Vm - var_I_ERG__E_K); // current_units
            const double var_ICC_Membrane__I_ERG = var_I_ERG__I_ERG; // current_units
            const double var_I_CaCl__Vm = var_ICC_Membrane__Vm; // voltage_units
            const double var_I_CaCl__Cl_o = var_ICC_Membrane__Cl_o; // millimolar
            const double var_I_CaCl__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_CaCl__Cl_i = var_ICC_Membrane__Cl_i; // millimolar
            const double var_I_CaCl__E_Cl = var_I_CaCl__RToF * log(var_I_CaCl__Cl_i / var_I_CaCl__Cl_o); // voltage_units
            const double var_I_CaCl__G_max_CaCl = 10.1; // conductance_units
            const double var_I_CaCl__I_CaCl = var_I_CaCl__G_max_CaCl * var_I_CaCl__d_CaCl * (var_I_CaCl__Vm - var_I_CaCl__E_Cl); // current_units
            const double var_ICC_Membrane__I_CaCl = var_I_CaCl__I_CaCl; // current_units
            const double var_I_NSCC__Vm = var_ICC_Membrane__Vm; // voltage_units
            const double var_I_NSCC__K_o = var_ICC_Membrane__K_o; // millimolar
            const double var_I_NSCC__Na_i = var_ICC_Membrane__Na_i; // millimolar
            const double var_I_NSCC__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_NSCC__K_i = var_ICC_Membrane__K_i; // millimolar
            const double var_I_NSCC__NaPerm_o_Kperm = 1.0560750000000001; // dimensionless
            const double var_I_NSCC__Na_o = var_ICC_Membrane__Na_o; // millimolar
            const double var_I_NSCC__E_NSCC = var_I_NSCC__RToF * log((var_I_NSCC__K_o + (var_I_NSCC__Na_o * var_I_NSCC__NaPerm_o_Kperm)) / (var_I_NSCC__K_i + (var_I_NSCC__Na_i * var_I_NSCC__NaPerm_o_Kperm))); // voltage_units
            const double var_I_NSCC__G_max_NSCC = 12.15; // conductance_units
            const double var_I_NSCC__I_NSCC = var_I_NSCC__G_max_NSCC * var_I_NSCC__d_NSCC * (var_I_NSCC__Vm - var_I_NSCC__E_NSCC); // current_units
            const double var_ICC_Membrane__I_NSCC = var_I_NSCC__I_NSCC; // current_units
            const double var_I_bk__Vm = var_ICC_Membrane__Vm; // voltage_units
            const double var_I_bk__G_max_bk = 0.14999999999999999; // conductance_units
            const double var_I_bk__K_i = var_ICC_Membrane__K_i; // millimolar
            const double var_I_bk__RToF = var_ICC_Membrane__RToF; // voltage_units
            const double var_I_bk__K_o = var_ICC_Membrane__K_o; // millimolar
            const double var_I_bk__E_K = var_I_bk__RToF * log(var_I_bk__K_o / var_I_bk__K_i); // voltage_units
            const double var_I_bk__I_bk = var_I_bk__G_max_bk * (var_I_bk__Vm - var_I_bk__E_K); // current_units
            const double var_ICC_Membrane__I_bk = var_I_bk__I_bk; // current_units
            const double var_ICC_Membrane__d_Vm_d_Time__time = (((-1.0) * 1.0) / var_ICC_Membrane__Cm) * (var_ICC_Membrane__I_Na + var_ICC_Membrane__I_Ltype + var_ICC_Membrane__I_VDDR + var_ICC_Membrane__I_kv11 + var_ICC_Membrane__I_ERG + var_ICC_Membrane__I_BK + var_ICC_Membrane__I_CaCl + var_ICC_Membrane__I_NSCC + var_ICC_Membrane__I_bk + (var_ICC_Membrane__J_PMCA * 2.0 * 1000000.0 * 1000000.0 * var_ICC_Membrane__F * var_ICC_Membrane__V_cyto)); // 'millivolt per second'
            const double var_chaste_interface__ICC_Membrane__d_Vm_d_Time__time_converter = var_ICC_Membrane__d_Vm_d_Time__time; // ___units_11
            const double var_chaste_interface__ICC_Membrane__d_Vm_d_Time__time = 0.001 * var_chaste_interface__ICC_Membrane__d_Vm_d_Time__time_converter; // 'millivolt per millisecond'
            d_dt_chaste_interface__ICC_Membrane__Vm = var_chaste_interface__ICC_Membrane__d_Vm_d_Time__time; // 'millivolt per millisecond'
        }
        
        rDY[0] = d_dt_chaste_interface__ICC_Membrane__Vm;
        rDY[1] = d_dt_chaste_interface__ICC_Membrane__Ca_i;
        rDY[2] = d_dt_chaste_interface__d_Ltype__d_Ltype;
        rDY[3] = d_dt_chaste_interface__f_Ltype__f_Ltype;
        rDY[4] = d_dt_chaste_interface__f_ca_Ltype__f_ca_Ltype;
        rDY[5] = d_dt_chaste_interface__d_VDDR__d_VDDR;
        rDY[6] = d_dt_chaste_interface__f_VDDR__f_VDDR;
        rDY[7] = d_dt_chaste_interface__d_CaCl__d_CaCl;
        rDY[8] = d_dt_chaste_interface__d_ERG__d_ERG;
        rDY[9] = d_dt_chaste_interface__d_kv11__d_kv11;
        rDY[10] = d_dt_chaste_interface__f_kv11__f_kv11;
        rDY[11] = d_dt_chaste_interface__d_Na__d_Na;
        rDY[12] = d_dt_chaste_interface__f_Na__f_Na;
        rDY[13] = d_dt_chaste_interface__d_NSCC__d_NSCC;
        rDY[14] = d_dt_chaste_interface__PU_unit__Ca_PU;
        rDY[15] = d_dt_chaste_interface__PU_unit__Ca_m;
        rDY[16] = d_dt_chaste_interface__PU_unit__Ca_ER;
        rDY[17] = d_dt_chaste_interface__PU_unit__ADP_m;
        rDY[18] = d_dt_chaste_interface__PU_unit__ADP_i;
        rDY[19] = d_dt_chaste_interface__PU_unit__NADH_m;
        rDY[20] = d_dt_chaste_interface__PU_unit__h;
        rDY[21] = d_dt_chaste_interface__PU_unit__deltaPsi;
    }
    
template<>
void OdeSystemInformation<Cellcorrias_buist_2008FromCellML>::Initialise(void)
{
    this->mSystemName = "ICC_model";
    this->mFreeVariableName = "time";
    this->mFreeVariableUnits = "millisecond";
    
    // rY[0]:
    this->mVariableNames.push_back("membrane_voltage");
    this->mVariableUnits.push_back("millivolt");
    this->mInitialConditions.push_back(-67);

    // rY[1]:
    this->mVariableNames.push_back("ICC_Membrane__Ca_i");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.00000993087);

    // rY[2]:
    this->mVariableNames.push_back("d_Ltype__d_Ltype");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[3]:
    this->mVariableNames.push_back("f_Ltype__f_Ltype");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1);

    // rY[4]:
    this->mVariableNames.push_back("f_ca_Ltype__f_ca_Ltype");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1);

    // rY[5]:
    this->mVariableNames.push_back("d_VDDR__d_VDDR");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[6]:
    this->mVariableNames.push_back("f_VDDR__f_VDDR");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1);

    // rY[7]:
    this->mVariableNames.push_back("d_CaCl__d_CaCl");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[8]:
    this->mVariableNames.push_back("d_ERG__d_ERG");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[9]:
    this->mVariableNames.push_back("d_kv11__d_kv11");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[10]:
    this->mVariableNames.push_back("f_kv11__f_kv11");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1);

    // rY[11]:
    this->mVariableNames.push_back("d_Na__d_Na");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[12]:
    this->mVariableNames.push_back("f_Na__f_Na");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1);

    // rY[13]:
    this->mVariableNames.push_back("d_NSCC__d_NSCC");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    // rY[14]:
    this->mVariableNames.push_back("PU_unit__Ca_PU");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.0000902);

    // rY[15]:
    this->mVariableNames.push_back("PU_unit__Ca_m");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.000136);

    // rY[16]:
    this->mVariableNames.push_back("PU_unit__Ca_ER");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.007299);

    // rY[17]:
    this->mVariableNames.push_back("PU_unit__ADP_m");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(2.60093454);

    // rY[18]:
    this->mVariableNames.push_back("PU_unit__ADP_i");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.0077282);

    // rY[19]:
    this->mVariableNames.push_back("PU_unit__NADH_m");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.101476);

    // rY[20]:
    this->mVariableNames.push_back("PU_unit__h");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9397);

    // rY[21]:
    this->mVariableNames.push_back("PU_unit__deltaPsi");
    this->mVariableUnits.push_back("voltage_units");
    this->mInitialConditions.push_back(164.000044);

    this->mInitialised = true;
}


// Serialization for Boost >= 1.36
#include "SerializationExportWrapperForCpp.hpp"
CHASTE_CLASS_EXPORT(Cellcorrias_buist_2008FromCellML)
